### PR TITLE
Use noauth by default and dont show login and password

### PR DESCRIPTION
**Pull request by pawel-yesware**
This is a very hackish way to fix it but works well ^shrug^

### CODE REVIEW

**Comment by pawel-yesware** [comment]
@mkostick

**Comment by mkostick** [comment]
I'm worried about the hardcoded versions here.  Couldn't you make things conditional on something more generic like `${MONGODB_NO_AUTH}` and `${MONGODB_USE_ADDUSER}`?  We've already discussed doing specific configuration commands with some higher-level "start all my services" script.

**Comment by pawel-yesware** [comment]
I quite don't know how we can implement that in config file the other ones we can do check if MONGO_NO_AUTH 

what about something like this

```
if [[ $MONGO_NO_AUTH = "true" && $MONGO_IMAGE_VERSION = "2.4.14" ]]; then
    export MONGO_CONFIG_OPTIONS=${MONGO_CONFIG_OPTIONS:=" --noauth "}
else
    export MONGO_CONFIG_OPTIONS=${MONGO_CONFIG_OPTIONS:=" --storageEngine wiredTiger --noauth "}
fi
```

**Comment by pawel-yesware** [comment]
I did this if this way becasue version 2.4.x uses different storage engine

**Comment by mkostick** [comment]
I'd feel better about this if you were looking at major.minor instead of the full version in these conditionals.  Something like

```
MONGO_MAJOR_MINOR=`echo ${MONGO_IMAGE_VERSION} | sed -E 's/([0-9]+\.[0-9]+)\.[0-9]+/\1/'`
```

(or some prettier way of doing that!)

**Pull request closed without merging**
